[build]
  command = "pip install -r requirements-minimal.txt && streamlit run Medical_AI_Assistant.py"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200